src: Fix declaration of ldm_new
GCC 15 forbids declaring a function with () instead of (void).
Declaring it properly reveals an actual bug in ldmtool.

ldmtool.c: In function ‘main’:
ldmtool.c:859:23: error: too many arguments to function ‘ldm_new’; expected 0, have 1
  859 |     LDM * const ldm = ldm_new(&err);
      |                       ^~~~~~~ ~~~~
In file included from ldmtool.c:38:
ldm.h:259:6: note: declared here
  259 | LDM *ldm_new();
      |      ^~~~~~~